<div class="row">
    <div class="large-12 columns">
        <ul class="example-orbit" data-orbit>
        <li>
          <img src="http://foundation.zurb.com/docs/assets/img/examples/satelite-orbit.jpg" alt="slide 1" />
          <div class="orbit-caption">
            Caption One.
          </div>
        </li>
        <li>
          <img src="http://foundation.zurb.com/docs/assets/img/examples/andromeda-orbit.jpg" alt="slide 2" />
          <div class="orbit-caption">
            Caption Two.
          </div>
        </li>
        <li>
          <img src="http://foundation.zurb.com/docs/assets/img/examples/launch-orbit.jpg" alt="slide 3" />
          <div class="orbit-caption">
            Caption Three.
          </div>
        </li>
      </ul>
    </div>
</div>