<div class="row">
    <div class="off-canvas-wrap">
        <div class="inner-wrap">
            <nav class="tab-bar hide-for-medium-up">
                <section class="left-small">
                    <a class="left-off-canvas-toggle menu-icon" href="#" ><span></span></a>
                </section>
            </nav>
            <aside class="left-off-canvas-menu">
                <?php echo $this->partial("partials/sidenav.phtml",["class"=>"off-canvas-list"]); ?>
            </aside>
            <div class="large-10 small-12 medium-10 columns">
                <div class="row">
                    <div class="large-12 small-12 columns">
                        <h2>Blog</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="small-2 large-2 columns">
                        <a class="th radius" href="#">
                            <img src="http://foundation.zurb.com/docs/assets/img/examples/earth.jpg">
                        </a>
                    </div>
                    <div class="large-10 small-10 columns">
                        <div class="panel">
                        <h3>Blog heading</h3>
                        <p>Lorem ipsum dolor sit amet, eu vis senserit rationibus intellegebat, ad vide placerat menandri ius, ad duis sententiae dissentiet qui. Ut vix nullam virtute diceret. An sea vide petentium, id ipsum veritus consulatu has. His sumo efficiendi at, te vel essent inermis nominavi. Te euismod phaedrum elaboraret his.

Accumsan similique consectetuer ex mel, nam quot laudem te, ex ius sonet simul persius. An vix mollis noluisse, duo ex affert dolore nominavi. Nec prompta inermis reformidans at. Dictas referrentur ex vix.

Eum error vocibus oporteat no, sit probo aeterno accusam at. Dicam animal minimum nec at. Eos eu blandit oportere, vim graece feugiat invidunt no. Illum veniam electram sea et, et sit graeco meliore forensibus. Ad nibh posse lobortis eum, tacimates liberavisse eu eam.

Ut sit iudico appetere efficiantur. Mea consequat consectetuer ne. Vix ne viderer inciderint, ut veri principes mea. Ius viris legere et.</p>
                        </div>
                        </div>
                 </div>
                   <div class="row">
                    <div class="small-2 large-2 columns">
                        <a class="th radius" href="#">
                            <img src="http://foundation.zurb.com/docs/assets/img/examples/earth.jpg">
                        </a>
                    </div>
                    <div class="large-10 small-10 columns">
                        <h3>Blog heading</h3>
                        <p>Lorem ipsum dolor sit amet, eu vis senserit rationibus intellegebat, ad vide placerat menandri ius, ad duis sententiae dissentiet qui. Ut vix nullam virtute diceret. An sea vide petentium, id ipsum veritus consulatu has. His sumo efficiendi at, te vel essent inermis nominavi. Te euismod phaedrum elaboraret his.

Accumsan similique consectetuer ex mel, nam quot laudem te, ex ius sonet simul persius. An vix mollis noluisse, duo ex affert dolore nominavi. Nec prompta inermis reformidans at. Dictas referrentur ex vix.

Eum error vocibus oporteat no, sit probo aeterno accusam at. Dicam animal minimum nec at. Eos eu blandit oportere, vim graece feugiat invidunt no. Illum veniam electram sea et, et sit graeco meliore forensibus. Ad nibh posse lobortis eum, tacimates liberavisse eu eam.

Ut sit iudico appetere efficiantur. Mea consequat consectetuer ne. Vix ne viderer inciderint, ut veri principes mea. Ius viris legere et.</p>
                    </div>
                 </div>
                <div class="row">
                    <div class="small-2 large-2 columns">
                        <a class="th radius" href="#">
                            <img src="http://foundation.zurb.com/docs/assets/img/examples/earth.jpg">
                        </a>
                    </div>
                    <div class="large-10 small-10 columns">
                        <h3>Blog heading</h3>
                        <p>Lorem ipsum dolor sit amet, eu vis senserit rationibus intellegebat, ad vide placerat menandri ius, ad duis sententiae dissentiet qui. Ut vix nullam virtute diceret. An sea vide petentium, id ipsum veritus consulatu has. His sumo efficiendi at, te vel essent inermis nominavi. Te euismod phaedrum elaboraret his.

Accumsan similique consectetuer ex mel, nam quot laudem te, ex ius sonet simul persius. An vix mollis noluisse, duo ex affert dolore nominavi. Nec prompta inermis reformidans at. Dictas referrentur ex vix.

Eum error vocibus oporteat no, sit probo aeterno accusam at. Dicam animal minimum nec at. Eos eu blandit oportere, vim graece feugiat invidunt no. Illum veniam electram sea et, et sit graeco meliore forensibus. Ad nibh posse lobortis eum, tacimates liberavisse eu eam.

Ut sit iudico appetere efficiantur. Mea consequat consectetuer ne. Vix ne viderer inciderint, ut veri principes mea. Ius viris legere et.</p>
                    </div>
                 </div>
                
            </div>
            <div class="large-2 small-2 medium-2 columns hide-for-small">
                <?php echo $this->partial("partials/sidenav.phtml",["title"=>"Blog","class"=>"side-nav"]); ?>
            </div>
            <a class="exit-off-canvas"></a>
        </div>
    </div>
</div>
<?php $this->inlinescript()->appendFile($this->basePath('js/foundation/foundation.offcanvas.js'));