<div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name"></li>
            <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
        </ul>
        <section class="top-bar-section">
            <ul class="right">
                <li class="has-form">
                    <form method="get" action="/search">
                        <div class="row collapse">
                                <div class="large-8 small-9 columns">
                                    <input type="text" placeholder="Find Stuff">
                                </div>
                                <div class="large-4 small-3 columns">
                                  <a href="#" class="alert button expand">Search</a>
                                </div>
                          </div> 
                    </form>
                </li>
            </ul>
            <ul class="left">
                <li><a href="/">Link 1</a></li>
                <li><a href="/">Link 1</a></li>
                <li><a href="/">Link 1</a></li>
                <li><a href="/">Link 1</a></li>
                <li class="divider"></li>
            </ul>
        </section>
    </nav>
</div>