<form data-abide>
    <div class="row">
        <div class="large-12 columns">
        <div data-alert class="alert-box alert round">
            Some items were missed in the form - please fix
            <a href="#" class="close">&times;</a>
          </div>
        </div>
    </div>
    <div class="row">
        <div class="large-4 small-12 medium-4 columns">
            <label>First name <span class="asterix">*</span>
                <input type="text" class="radius" placeholder="Form Field" required/>
            </label>
            <small class="error">Please provide your first name</small>
        </div>
        <div class="large-4 small-12 medium-4 columns">
            <label>Password <span class="asterix">*</span>
                <input type="password" class="radius" placeholder="Password" name="password" id="password" required/>
            </label>
            <small class="error">Please enter your password</small>
        </div>
        <div class="large-4 small-12 medium-4 columns">
            <label>Confirm Password <span class="asterix">*</span>
                <input type="password" class="radius" placeholder="Password Confirm" name="password confirm" required data-equalto="password"/>
            </label>
            <small class="error">The passwords must match</small>
        </div>
        
    </div>
    <div class="row">
        <div class="large-4 small-12 medium-12 columns">
            <label>anything else?
                <input type="text" class="radius" placeholder="Form Field" />
            </label>
        </div>
    </div> 
    <div class="row">
        <div class="large-12 small-12 medium-12 columns">
            <button type="submit" class="radius">Submit</button>
        </div>
    </div>
</form>