<div class="footer">
    <div class="row">
        <div class="large-12 columns">
            <h1>Footer</h1>
        </div>
    </div>
</div>
<?php
echo $this->inlineScript()->prependFile($this->basePath('assets/Foundation/js/foundation.min.js'))
                          ->prependFile($this->basePath('assets/Foundation/js/foundation.footer.js'))
                          ->prependFile($this->basePath('assets/jquery/ui/jquery-ui-1.10.4.custom.min.js'))
                          ->prependFile($this->basePath('assets/jquery/v11/jquery.11.js'));                    
?>
<script>
  $(document).foundation();
</script>
</body>
</html>