<!--[if lt IE 7]> <html class="ie6 oldie"> <![endif]-->
<!--[if IE 7]>    <html class="ie7 oldie"> <![endif]-->
<!--[if IE 8]>    <html class="ie8 oldie"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Language" content="en">
<meta name="author" content="WebSpring Ltd">
<meta name="robots" content="INDEX,FOLLOW">
<meta name="title" content="">
<meta name="og:title" content="">
<meta name="og:type" content="webpage">
<meta name="keywords" content="">
<meta name="description" content="">               
<title><?php echo $this->title; ?></title> 
<link href="<?php echo $this->basePath("favicon.ico");?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
<?php 
    echo $this->HeadLink()
                ->prependFile($this->basePath("assets/Foundation/css/normalize.css"))
                ->prependFile($this->basePath("assets/Foundation/css/stickyfooter.css"))
                ->appendFile($this->basePath("assets/Foundation/css/foundation.min.css"));
    echo $this->headScript()
                ->appendFile($this->basePath("assets/modernizr/v1/modernizr.js"));
?>
</head>
<body>  
<?php //echo $this->partial('partials/analytics.phtml'); ?>  